### ISSUE TITLE
Plugin doesn't work with Admin Manager?

### ISSUE THREAD

**Issue by ViliusS** [trilbymedia/grav-plugin-login-ldap#17]
Doesn't this plugin work with Admin Panel? I've set it up to successfully authenticate against site pages, but if I try to view https://mysite.example.net/admin it goes into Exception straight away.

`Could not complete search with dn "dc=example,dc=net", query "sAMAccountName=" and filters "*".`

Looks like it tries to authenticate before I even can see the login screen?

**Comment by ViliusS** [comment]
Just found this PR https://github.com/trilbymedia/grav-plugin-login-ldap/pull/14 Looks like it was never released.

**Comment by rhukster** [comment]
I've added it to my list of things to release.  Thanks.
