### ISSUE TITLE
Additional fields from LDAP

### ISSUE THREAD

**Issue by bkraegelin** [trilbymedia/grav-plugin-login-ldap#21]
Please provide a way to show (and edit ?) additional user attributes.

The Login plugin https://github.com/getgrav/grav-plugin-login allows for additional registration fields, which I map to LDAP attributes. The other way round, I want to read these attributes on LDAP login and provide them in the user object, so I can access the values in my own plugin/in event hooks.

Thanks,
Birger

**Comment by bkraegelin** [comment]
I found options **_save_grav_user_** and **_store_ldap_data_** and successfully verified it.
I had to read the source code to understand it correctly.

Thanks.

**Comment by viharm** [comment]
What are the fields extracted from the LDAP server? Currently `mail` is being extracted and mapped to _Grav_ `email`, but the avatar image isn't being extracted from `jpegPhoto`.

It would be good to know what are the LDAP fields extracted from the server.

.... and ideal to be able to configure mappings :-)
